# Generated by Django 4.2.2 on 2023-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.AlterField(
            model_name="task",
            name="task_no",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
